name: Smoke Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
  
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install Node.js dependencies
        run: |
          npm install

      - id: smoke_test
        name: Smoke Test generator-options, test-generators and forge commands
        run: |
          npm run test:smoke

      - id: show_full_log
        name: Show Full Log
        if: success() || failure()
        run: |
          cat log.txt