name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-generators:
    name: Test
    runs-on: windows-latest 

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

        # Must change shell because this workflow uses the windows-latest image 
      - name: Set npm shell
        run: npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"

      - name: Check out openapi-forge repository
        uses: actions/checkout@v3
        with: 
          path: openapi-forge

      - name: Install openapi-forge dependencies globally
        run: |
          cd openapi-forge
          npm install
          npm install --global

      - name: Check out the openapi-forge-javascript generator
        uses: actions/checkout@v3
        with: 
          repository: ScottLogic/openapi-forge-javascript
          path: openapi-forge-javascript

      - name: Install openapi-forge-javascript dependencies
        run: |
          cd openapi-forge-javascript
          npm install

      - name: Check out the openapi-forge-csharp generator
        uses: actions/checkout@v3
        with: 
          repository: ScottLogic/openapi-forge-csharp
          path: openapi-forge-csharp

      - name: Install openapi-forge-csharp dependencies
        run: |
          cd openapi-forge-csharp
          npm install

      - name: Check out the openapi-forge-typescript generator
        uses: actions/checkout@v3
        with: 
          repository: ScottLogic/openapi-forge-typescript
          path: openapi-forge-typescript

      - name: Install openapi-forge-typescript dependencies
        run: |
          cd openapi-forge-typescript
          npm install

      - name: Test generators
        run: |
          cd openapi-forge
          openapi-forge test-generators --format json --generators openapi-forge-javascript openapi-forge-typescript openapi-forge-csharp > test-results.json
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: openapi-forge/test-results.json


          # NO CHECKS ON THE CONTENTS OF test-results.json!!! Could be erroneously passing.