name: Test Forge

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test-forge:
    name: Test Forge
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install openapi-forge dependencies locally
        run: |
          npm install
      - name: Test Forge
        run: |
          npm run test
        continue-on-error: true